### ISSUE TITLE
Include doesnt work in parallel files

### ISSUE THREAD

**Issue by ThunderSphun** [Settis/dasm-vscode#57]
I have a structure like this:
```
entry.asm
constants.asm
code.asm
```
`entry.asm`:
```
include constants.asm
include code.asm
```
`constants.asm`:
```
SOME_CONST EQU $0001
```
`code.asm`:
```
LDA SOME_CONST ; doesn't know SOME_CONST (label is not defined)
```
This would build by dasm, but would give errors by this extension

**Comment by Settis** [comment]
This will be fixed in the next release.

The plugin can't predict what the file you are using as a root for compilation. You need to keep it opened. Here is related Wiki page: [Working with multi-file program](https://github.com/Settis/dasm-vscode/wiki/Working-with-multi-file-program).
