### ISSUE TITLE
Relocatable origins not supported

### ISSUE THREAD

**Issue by ThunderSphun** [Settis/dasm-vscode#58]
DASM has an upcode RORG for relocatable origins and REND for end of this relocatable origin.
These upcodes are not included in this extension

**Comment by Settis** [comment]
Never used it and for me it was not clear from the doc what exactly this thing is doing.
I've found example here in [6502 forum](http://forum.6502.org/viewtopic.php?f=12&t=6986&sid=a0d0975acceaf7511233a1b73563fab5#p90412).
Updated it with what seems to be non valid `rend` and `rorg`.
```
            processor 6502
            org $1000    ; bank1 starts at file position 0, memory address $1000
bank1       jmp bank1    ; jmp $1000
            rend ; WARNING? closing relocatable but there is no RORG before

            org $2000    ; bank2 continues at file at position $1000, memory address $2000
            rorg $1000   ; but code thinks it is located at $1000
bank2       jmp bank2    ; assembles as "jmp $1000", would be "jmp $2000" without the RORG
            
            rorg $1000 ; WARNING? Open another RORG without ending the previous one
            LDA #45
```
DASM gives no error on it. And it seems that I can ignore those too.
Does it make sense to show warnings when the programmer tries to close a non-opened relocatable or starts it twice without closing?
What do you think? Maybe warnings will help programmers, but perhaps there are tons of existing programs where no one cared about the right opening/closing order and with this check, the source will be full of warnings.

**Comment by ThunderSphun** [comment]
i think warnings would be usefull
